security:
    providers:
        jwt_user_provider:
            id: jwt_user_provider

    firewalls:
        jwt_secured_area:
            pattern: ^/protected
            stateless: true
            simple_preauth:
                authenticator: jwt_authenticator
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }