export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const RECEIVE_VERSIONS = 'RECEIVE_VERSIONS';
export const RECEIVE_VERSION = 'RECIEVE_VERSION';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const DELETE_VERSION = 'DELETE_VERSION';
export const REPLACE_VERSION = 'REPLACE_VERSION';
export const MOVE_VERSION = 'MOVE_VERSION';
